// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/testsection/testsection.proto

package testsectionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TestSectionService_CreateTest_FullMethodName = "/test.TestSectionService/CreateTest"
	TestSectionService_GetTest_FullMethodName    = "/test.TestSectionService/GetTest"
)

// TestSectionServiceClient is the client API for TestSectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC service
type TestSectionServiceClient interface {
	CreateTest(ctx context.Context, in *CreateTestRequest, opts ...grpc.CallOption) (*CreateTestResponse, error)
	GetTest(ctx context.Context, in *GetTestRequest, opts ...grpc.CallOption) (*GetTestResponse, error)
}

type testSectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestSectionServiceClient(cc grpc.ClientConnInterface) TestSectionServiceClient {
	return &testSectionServiceClient{cc}
}

func (c *testSectionServiceClient) CreateTest(ctx context.Context, in *CreateTestRequest, opts ...grpc.CallOption) (*CreateTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTestResponse)
	err := c.cc.Invoke(ctx, TestSectionService_CreateTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testSectionServiceClient) GetTest(ctx context.Context, in *GetTestRequest, opts ...grpc.CallOption) (*GetTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTestResponse)
	err := c.cc.Invoke(ctx, TestSectionService_GetTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestSectionServiceServer is the server API for TestSectionService service.
// All implementations must embed UnimplementedTestSectionServiceServer
// for forward compatibility.
//
// gRPC service
type TestSectionServiceServer interface {
	CreateTest(context.Context, *CreateTestRequest) (*CreateTestResponse, error)
	GetTest(context.Context, *GetTestRequest) (*GetTestResponse, error)
	mustEmbedUnimplementedTestSectionServiceServer()
}

// UnimplementedTestSectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTestSectionServiceServer struct{}

func (UnimplementedTestSectionServiceServer) CreateTest(context.Context, *CreateTestRequest) (*CreateTestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTest not implemented")
}
func (UnimplementedTestSectionServiceServer) GetTest(context.Context, *GetTestRequest) (*GetTestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTest not implemented")
}
func (UnimplementedTestSectionServiceServer) mustEmbedUnimplementedTestSectionServiceServer() {}
func (UnimplementedTestSectionServiceServer) testEmbeddedByValue()                            {}

// UnsafeTestSectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestSectionServiceServer will
// result in compilation errors.
type UnsafeTestSectionServiceServer interface {
	mustEmbedUnimplementedTestSectionServiceServer()
}

func RegisterTestSectionServiceServer(s grpc.ServiceRegistrar, srv TestSectionServiceServer) {
	// If the following call pancis, it indicates UnimplementedTestSectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TestSectionService_ServiceDesc, srv)
}

func _TestSectionService_CreateTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestSectionServiceServer).CreateTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestSectionService_CreateTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestSectionServiceServer).CreateTest(ctx, req.(*CreateTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestSectionService_GetTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestSectionServiceServer).GetTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestSectionService_GetTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestSectionServiceServer).GetTest(ctx, req.(*GetTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TestSectionService_ServiceDesc is the grpc.ServiceDesc for TestSectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestSectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test.TestSectionService",
	HandlerType: (*TestSectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTest",
			Handler:    _TestSectionService_CreateTest_Handler,
		},
		{
			MethodName: "GetTest",
			Handler:    _TestSectionService_GetTest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/testsection/testsection.proto",
}
