// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/testsection/testsection.proto

package testsectionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Test yaratish request
type CreateTestRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TeacherTelegramId int64                  `protobuf:"varint,1,opt,name=teacher_telegram_id,json=teacherTelegramId,proto3" json:"teacher_telegram_id,omitempty"`
	TestId            string                 `protobuf:"bytes,2,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Questions         []*Question            `protobuf:"bytes,3,rep,name=questions,proto3" json:"questions,omitempty"` // JSON massiv sifatida yuboriladi
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTestRequest) Reset() {
	*x = CreateTestRequest{}
	mi := &file_proto_testsection_testsection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTestRequest) ProtoMessage() {}

func (x *CreateTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testsection_testsection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTestRequest.ProtoReflect.Descriptor instead.
func (*CreateTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_testsection_testsection_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTestRequest) GetTeacherTelegramId() int64 {
	if x != nil {
		return x.TeacherTelegramId
	}
	return 0
}

func (x *CreateTestRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *CreateTestRequest) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

// Test yaratish response
type CreateTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTestResponse) Reset() {
	*x = CreateTestResponse{}
	mi := &file_proto_testsection_testsection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTestResponse) ProtoMessage() {}

func (x *CreateTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testsection_testsection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTestResponse.ProtoReflect.Descriptor instead.
func (*CreateTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_testsection_testsection_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateTestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Test olish request
type GetTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    int64                  `protobuf:"varint,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	TestId        string                 `protobuf:"bytes,2,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestRequest) Reset() {
	*x = GetTestRequest{}
	mi := &file_proto_testsection_testsection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestRequest) ProtoMessage() {}

func (x *GetTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testsection_testsection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestRequest.ProtoReflect.Descriptor instead.
func (*GetTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_testsection_testsection_proto_rawDescGZIP(), []int{2}
}

func (x *GetTestRequest) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

func (x *GetTestRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

// Test olish response
type GetTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"` // Shu massivni qaytaradi
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestResponse) Reset() {
	*x = GetTestResponse{}
	mi := &file_proto_testsection_testsection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestResponse) ProtoMessage() {}

func (x *GetTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testsection_testsection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestResponse.ProtoReflect.Descriptor instead.
func (*GetTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_testsection_testsection_proto_rawDescGZIP(), []int{3}
}

func (x *GetTestResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *GetTestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Question (Redisdagi JSON massivdan olingan)
// options => variants []string ga convert qilinadi service layerda
type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Variants      []string               `protobuf:"bytes,2,rep,name=variants,proto3" json:"variants,omitempty"`                                // faqat textlarini olamiz
	CorrectAnswer string                 `protobuf:"bytes,3,opt,name=correct_answer,json=correctAnswer,proto3" json:"correct_answer,omitempty"` // Telegram ID mos kelmasa, bo‘sh string beriladi
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_proto_testsection_testsection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testsection_testsection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_proto_testsection_testsection_proto_rawDescGZIP(), []int{4}
}

func (x *Question) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Question) GetVariants() []string {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *Question) GetCorrectAnswer() string {
	if x != nil {
		return x.CorrectAnswer
	}
	return ""
}

var File_proto_testsection_testsection_proto protoreflect.FileDescriptor

const file_proto_testsection_testsection_proto_rawDesc = "" +
	"\n" +
	"#proto/testsection/testsection.proto\x12\x04test\"\x8a\x01\n" +
	"\x11CreateTestRequest\x12.\n" +
	"\x13teacher_telegram_id\x18\x01 \x01(\x03R\x11teacherTelegramId\x12\x17\n" +
	"\atest_id\x18\x02 \x01(\tR\x06testId\x12,\n" +
	"\tquestions\x18\x03 \x03(\v2\x0e.test.QuestionR\tquestions\"H\n" +
	"\x12CreateTestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"J\n" +
	"\x0eGetTestRequest\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\x03R\n" +
	"telegramId\x12\x17\n" +
	"\atest_id\x18\x02 \x01(\tR\x06testId\"Y\n" +
	"\x0fGetTestResponse\x12,\n" +
	"\tquestions\x18\x01 \x03(\v2\x0e.test.QuestionR\tquestions\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"i\n" +
	"\bQuestion\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x1a\n" +
	"\bvariants\x18\x02 \x03(\tR\bvariants\x12%\n" +
	"\x0ecorrect_answer\x18\x03 \x01(\tR\rcorrectAnswer2\x8d\x01\n" +
	"\x12TestSectionService\x12?\n" +
	"\n" +
	"CreateTest\x12\x17.test.CreateTestRequest\x1a\x18.test.CreateTestResponse\x126\n" +
	"\aGetTest\x12\x14.test.GetTestRequest\x1a\x15.test.GetTestResponseBGZEgithub.com/khbdev/arena-startup-proto/proto/testsection/testsectionpbb\x06proto3"

var (
	file_proto_testsection_testsection_proto_rawDescOnce sync.Once
	file_proto_testsection_testsection_proto_rawDescData []byte
)

func file_proto_testsection_testsection_proto_rawDescGZIP() []byte {
	file_proto_testsection_testsection_proto_rawDescOnce.Do(func() {
		file_proto_testsection_testsection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_testsection_testsection_proto_rawDesc), len(file_proto_testsection_testsection_proto_rawDesc)))
	})
	return file_proto_testsection_testsection_proto_rawDescData
}

var file_proto_testsection_testsection_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_testsection_testsection_proto_goTypes = []any{
	(*CreateTestRequest)(nil),  // 0: test.CreateTestRequest
	(*CreateTestResponse)(nil), // 1: test.CreateTestResponse
	(*GetTestRequest)(nil),     // 2: test.GetTestRequest
	(*GetTestResponse)(nil),    // 3: test.GetTestResponse
	(*Question)(nil),           // 4: test.Question
}
var file_proto_testsection_testsection_proto_depIdxs = []int32{
	4, // 0: test.CreateTestRequest.questions:type_name -> test.Question
	4, // 1: test.GetTestResponse.questions:type_name -> test.Question
	0, // 2: test.TestSectionService.CreateTest:input_type -> test.CreateTestRequest
	2, // 3: test.TestSectionService.GetTest:input_type -> test.GetTestRequest
	1, // 4: test.TestSectionService.CreateTest:output_type -> test.CreateTestResponse
	3, // 5: test.TestSectionService.GetTest:output_type -> test.GetTestResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_testsection_testsection_proto_init() }
func file_proto_testsection_testsection_proto_init() {
	if File_proto_testsection_testsection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_testsection_testsection_proto_rawDesc), len(file_proto_testsection_testsection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_testsection_testsection_proto_goTypes,
		DependencyIndexes: file_proto_testsection_testsection_proto_depIdxs,
		MessageInfos:      file_proto_testsection_testsection_proto_msgTypes,
	}.Build()
	File_proto_testsection_testsection_proto = out.File
	file_proto_testsection_testsection_proto_goTypes = nil
	file_proto_testsection_testsection_proto_depIdxs = nil
}
