// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/test-section/test-section.proto

package test_sectionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserTestResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    int64                  `protobuf:"varint,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	TestId        string                 `protobuf:"bytes,2,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTestResultRequest) Reset() {
	*x = GetUserTestResultRequest{}
	mi := &file_proto_test_section_test_section_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTestResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTestResultRequest) ProtoMessage() {}

func (x *GetUserTestResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_section_test_section_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTestResultRequest.ProtoReflect.Descriptor instead.
func (*GetUserTestResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_test_section_test_section_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserTestResultRequest) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

func (x *GetUserTestResultRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

type GetUserTestResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonData      string                 `protobuf:"bytes,1,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTestResultResponse) Reset() {
	*x = GetUserTestResultResponse{}
	mi := &file_proto_test_section_test_section_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTestResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTestResultResponse) ProtoMessage() {}

func (x *GetUserTestResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_test_section_test_section_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTestResultResponse.ProtoReflect.Descriptor instead.
func (*GetUserTestResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_test_section_test_section_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserTestResultResponse) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

var File_proto_test_section_test_section_proto protoreflect.FileDescriptor

const file_proto_test_section_test_section_proto_rawDesc = "" +
	"\n" +
	"%proto/test-section/test-section.proto\x12\x06result\"T\n" +
	"\x18GetUserTestResultRequest\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\x03R\n" +
	"telegramId\x12\x17\n" +
	"\atest_id\x18\x02 \x01(\tR\x06testId\"8\n" +
	"\x19GetUserTestResultResponse\x12\x1b\n" +
	"\tjson_data\x18\x01 \x01(\tR\bjsonData2i\n" +
	"\rResultService\x12X\n" +
	"\x11GetUserTestResult\x12 .result.GetUserTestResultRequest\x1a!.result.GetUserTestResultResponseBIZGgithub.com/khbdev/arena-startup-proto/proto/test-section/test-sectionpbb\x06proto3"

var (
	file_proto_test_section_test_section_proto_rawDescOnce sync.Once
	file_proto_test_section_test_section_proto_rawDescData []byte
)

func file_proto_test_section_test_section_proto_rawDescGZIP() []byte {
	file_proto_test_section_test_section_proto_rawDescOnce.Do(func() {
		file_proto_test_section_test_section_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_test_section_test_section_proto_rawDesc), len(file_proto_test_section_test_section_proto_rawDesc)))
	})
	return file_proto_test_section_test_section_proto_rawDescData
}

var file_proto_test_section_test_section_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_test_section_test_section_proto_goTypes = []any{
	(*GetUserTestResultRequest)(nil),  // 0: result.GetUserTestResultRequest
	(*GetUserTestResultResponse)(nil), // 1: result.GetUserTestResultResponse
}
var file_proto_test_section_test_section_proto_depIdxs = []int32{
	0, // 0: result.ResultService.GetUserTestResult:input_type -> result.GetUserTestResultRequest
	1, // 1: result.ResultService.GetUserTestResult:output_type -> result.GetUserTestResultResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_test_section_test_section_proto_init() }
func file_proto_test_section_test_section_proto_init() {
	if File_proto_test_section_test_section_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_test_section_test_section_proto_rawDesc), len(file_proto_test_section_test_section_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_test_section_test_section_proto_goTypes,
		DependencyIndexes: file_proto_test_section_test_section_proto_depIdxs,
		MessageInfos:      file_proto_test_section_test_section_proto_msgTypes,
	}.Build()
	File_proto_test_section_test_section_proto = out.File
	file_proto_test_section_test_section_proto_goTypes = nil
	file_proto_test_section_test_section_proto_depIdxs = nil
}
